options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'window-estimate'
      - '--source'
      - '.'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - 'stacking-492708'
